### ISSUE TITLE
Leaderboard defaulted to "Group" not displaying on homescreen

### ISSUE THREAD

**Issue by eshedroff** [ThoreBor/Anki_Leaderboard#207] opened 2023-03-08 22:45 UTC
Using macOS Cataline 10.15.7 and ANKI 2.1.60

Went into Tools -> Add-ons -> Leaderboard -> Config -> Settings

Checked box that says "display leaderboard on homepage" and set default leaderboard to "group"

Note I also have the ANKI heatmap and StatsPlus Add-ons enabled. Maybe they're potentially incompatible?

<img width="928" alt="Screen Shot 2023-03-08 at 5 45 44 PM" src="https://user-images.githubusercontent.com/78808529/223868632-91edeee2-c18e-4474-b8a8-9405af69c512.png">

**Comment by ThoreBor** [comment] 2023-03-10 12:54
Duplicate of #201. It's already fixed on GitHub, and will be included in the next update once I have time.

**Closed by ThoreBor** 2023-03-10 12:54 UTC
Labels: duplicate
