### ISSUE TITLE
Delay Upon Closing Anki

### ISSUE THREAD

**Issue by nmeed** [ThoreBor/Anki_Leaderboard#64] opened 2020-04-29 21:14 UTC
<img width="443" alt="Screen Shot 2020-04-30 at 12 47 40 AM" src="https://user-images.githubusercontent.com/37801365/80654343-4962a200-8a7c-11ea-9acd-b378a686108f.png">
When I close Anki, it will remain in the dock (Mac) for a good 3-4 minutes after I close it. If I delete Leaderboard, it closes immediately as it always had. This only occurred after upgrading to 2.1.24. Leaderboard version 1.4.4. Also note, this only occurs if I open Leaderboard. If I just use Anki without actually opening Leaderboard, this issue does not arise. It's almost as if Leaderboard keeps on running or something preventing Anki from closing....

**Comment by ThoreBor** [comment] 2020-04-30 07:04
Did you close the Leaderboard before closing Anki or was is still open?

**Comment by ThoreBor** [comment] 2020-04-30 07:26
I was able to reproduce the issue when I closed Anki while the Leaderboard was still open. The reason for that is probably that the add-on is  running on a background thread. You should be able to avoid this problem if you close the add-on before closing anki. However if this bothers you, just download the Leaderboard v.1.4.4b.ankiaddon file from github (see releases).
I'll try to fix this in the next release.

**Comment by nmeed** [comment] 2020-04-30 11:05
I did close Leaderboard before closing Anki. I also deleted the add-on and re-installed it several times in the hope it would fix the issue to no avail. I do not have this issue with 1.4.4b...thank you.

**Comment by ThoreBor** [comment] 2020-04-30 11:41
Okay, thanks for letting me know.

**Comment by ThoreBor** [comment] 2020-04-30 13:41
You could try if this fixes your problem. It worked for me.

https://drive.google.com/open?id=1b_QeVKs_W6Q4MXjZjnS-jkXkVPPJ-NMV

**Comment by nmeed** [comment] 2020-04-30 15:12
> You could try if this fixes your problem. It worked for me.
> 
> https://drive.google.com/open?id=1b_QeVKs_W6Q4MXjZjnS-jkXkVPPJ-NMV

Worked for me too! Thank you!

**Comment by ThoreBor** [comment] 2020-04-30 18:06
Great, in the next update it'll be officially fixed then.

**Closed by ThoreBor** 2020-04-30 18:06 UTC
Labels: bug
