### ISSUE TITLE
Anki leaderboard not showing on homescreen

### ISSUE THREAD

**Issue by meg4nfowler** [ThoreBor/Anki_Leaderboard#206] opened 2023-03-06 01:06 UTC
Anki leaderboard not showing on homescreen. 

<img width="518" alt="Screenshot 2023-03-06 at 12 05 56 pm" src="https://user-images.githubusercontent.com/127063838/222997659-ebe55cbf-605e-4b7a-b9fb-f01d6ea14450.png">

**Comment by ThoreBor** [comment] 2023-03-10 12:57
Duplicate of #201. It's already fixed on GitHub, and will be included in the next update once I have time. 
It should work with any other leaderboard besides groups in the meantime though.

**Closed by ThoreBor** 2023-03-10 12:57 UTC
Labels: duplicate
