### ISSUE TITLE
Some XP didn't got restarted at gamma league 

### ISSUE THREAD

**Issue by Jgneves** [ThoreBor/Anki_Leaderboard#114] opened 2020-10-17 14:50 UTC
**Describe the bug**
Hey, there! I really love this add-on, Thank you so much! 

The issue is that at gamma league, some people got the XP reseted (starting with 0 XP) and some people started with the same amount of XP they had at the end of the last season (much more XP)

As you can see in the image below, some people have a lot of minutes of study, but the season just started yesterday.

Thanks a LOT again for the add-on! You are helping me so much!!!! 
Obs: sorry about my English, I'm not from US

**Screenshots**
<img width="555" alt="image" src="https://user-images.githubusercontent.com/73028968/96339897-cce56f00-106d-11eb-9d17-9045a69a18f2.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/73028968/96340046-af64d500-106e-11eb-93ae-a2185e615f5c.png">

**Info**
- Anki version 2.1.35 
- Leaderboard version 1.6.0
- OS: macOS Catalina

**Comment by ThoreBor** [comment] 2020-10-17 15:14
Yes sorry, I'm aware of the problem but it's only temporarily. The issue is that some users synced old data after I reset everyone (my mistake). But once everyone restarted Anki and synced again everything should be back to normal. I already know what the issue is, so I'll fix it before the end of this season.
If it's really bothering you, could double click on those users and hide them and later unhide them, but like I said everything should look normal soon.

**Comment by Jgneves** [comment] 2020-10-17 18:50
Nice!!! Thank you so much for the prompt response. Its not bothering me at all, just didn't know if you knew that hahaha. This add-on is really great and the league idea is awesome! Thank you for this awesome job!!!!

**Comment by ThoreBor** [comment] 2020-10-30 12:11
Most people updated to v1.6.1 or v1.6.2 so this issue should be fixed for most users this season.

**Closed** 2020-11-02 15:24 UTC
Labels: bug
