### ISSUE TITLE
getdata bug

### ISSUE THREAD

**Issue by cornfed101** [ThoreBor/Anki_Leaderboard#149] opened 2021-08-07 15:23 UTC
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-06 13:23:02
Add-ons possibly involved: ⁨Leaderboard⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Welch/Library/Application Support/Anki2/addons21/41708974/__init__.py", line 100, in background_sync
    leaderboard_on_deck_browser()
  File "/Users/Welch/Library/Application Support/Anki2/addons21/41708974/lb_on_homescreen.py", line 258, in leaderboard_on_deck_browser
    DB.refresh()
  File "aqt/deckbrowser.py", line 72, in refresh
  File "aqt/deckbrowser.py", line 127, in _renderPage
  File "aqt/deckbrowser.py", line 136, in __renderPage
  File "aqt/hooks_gen.py", line 995, in __call__
  File "/Users/Welch/Library/Application Support/Anki2/addons21/41708974/lb_on_homescreen.py", line 121, in on_deck_browser_will_render_content
    lb = getData()
  File "/Users/Welch/Library/Application Support/Anki2/addons21/41708974/lb_on_homescreen.py", line 33, in getData
    for i in data:
TypeError: 'NoneType' object is not iterable

**Comment by Nanco300** [comment] 2021-08-08 13:25
Erro 
Ocorreu um erro. Por favor, inicialize Anki enquanto segura a tecla SHIFT, isto vai desabilitar temporariamente os complementos (add-ons) que você instalou. 
Se o problema ocorre somente quando os complementos estão habilitados, por favor vá para Ferramentas > Complementos e desabilite algum(s) complemento(s), para descobrir qual complemento é o responsável pelo problema. 
Assim que você descobrir o complemento responsável, por favor relate o problema na seção de complementos em nossa página de ajuda. 
Informação de Debug:
Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-08-08 10:21:44
Extensões possivelmente envolvidas: ⁨Leaderboard⁩

Caught exception:
Traceback (most recent call last):
  File "/home/maquiavelho/.local/share/Anki2/addons21/41708974/__init__.py", line 28, in Main
    mw.leaderboard = start_main(season_start, season_end, current_season)
  File "/home/maquiavelho/.local/share/Anki2/addons21/41708974/Leaderboard.py", line 41, in __init__
    self.setupUI()
  File "/home/maquiavelho/.local/share/Anki2/addons21/41708974/Leaderboard.py", line 97, in setupUI
    self.load_leaderboard()
  File "/home/maquiavelho/.local/share/Anki2/addons21/41708974/Leaderboard.py", line 212, in load_leaderboard
    for i in data:
TypeError: 'NoneType' object is not iterable

**Comment by ThoreBor** [comment] 2021-08-08 15:43
Do you get any errors before that?

**Comment by ThoreBor** [comment] 2021-08-08 18:30
I think I know what the issue is, and it should be fixed now

**Comment by cornfed101** [comment] 2021-08-08 19:07
That did it! Thanks

**Comment by ThoreBor** [comment] 2021-08-08 19:09
great🎉

**Closed by ThoreBor** 2021-08-08 19:09 UTC
Labels: bug
